---
timezone: America/Los_Angeles
locale: en_US.UTF-8
hostname: localhost
ssh_users: []
postgresql_admin_user: postgres

# mysql
mysql_port: 3306
mysql_bind_address: "127.0.0.1"
mysql_root_db_pass: null
mysql_conf_dir: "/etc/mysql"
mysql_repl_role: master
mysql_db_id: 7
mysql_db: []
mysql_users: []
mysql_repl_user: []
mysql_service: mysql

# Ruby
ruby_deploy_user: ubuntu
rbenv_makeopts: ""
# Which version we want to install (see `rbenv install -l`)
ruby_version: "2.2.2"

# Nginx

nginx_listen: 80

nginx_service: nginx

nginx_configure_ppa: true
nginx_spdy_enabled: true
nginx_names_hash_bucket_size: 32

nginx_base_domain: "{{ ansible_fqdn }}"
nginx_server_name: "{{ nginx_base_domain }}"
nginx_base_redirect_to_www: false

nginx_upstream_name: testproject
nginx_upstream_server: unix:///srv/{{ nginx_upstream_name }}/tmp/puma.sock
nginx_backend_name: puma

nginx_root_path: /srv/{{ nginx_upstream_name }}/public
nginx_assets_enabled: true
nginx_assets_regex: ~ ^/(system|assets)/

nginx_error_pages:
  - { error_code: 404, error_page: 404.html }
  - { error_code: 500, error_page: 500.html }
  - { error_code: 502 503 504, error_page: 502.html }

nginx_extra_locations: |
#  location / {
#    return;
#  }
#
#  location ~ ^/(images|javascript|js|css|flash|media|static)/ {
#    # directive 1 would go here;
#    # directive 2 would go here;
#    # ... add as many directives as you want;
#  }

nginx_ssl: false
nginx_listen_ssl: 443
nginx_server_redirect_to_ssl: false

nginx_ssl_type: selfsigned
nginx_ssl_ciphers: "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH+aRSA+RC4:EECDH:EDH+aRSA:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4"
nginx_ssl_ecdh_curve: secp384r1
nginx_ssl_wildcard_domain: "{{ ansible_domain }}"
nginx_ssl_strict_transport_header_age: 15768000
nginx_ssl_session_cache: shared:SSL:10m
nginx_ssl_session_timeout: 10m

nginx_ssl_manage_certs: true
nginx_ssl_local_path: /home/yourname/dev/testproject/secrets
nginx_ssl_cert_name: sslcert.crt
nginx_ssl_key_name: sslkey.key
nginx_ssl_protocols: "TLSv1 TLSv1.1 TLSv1.2"

apt_cache_valid_time: 86400
