---
timezone: America/Los_Angeles
locale: en_US.UTF-8
hostname: localhost
ssh_users: []
postgresql_admin_user: postgres

# mysql
mysql_port: 3306
mysql_bind_address: "127.0.0.1"
mysql_root_db_pass: null
mysql_conf_dir: "/etc/mysql"
mysql_repl_role: master
mysql_db_id: 7
mysql_db: []
mysql_users: []
mysql_repl_user: []
mysql_service: mysql


# Ruby
## stolen from https://github.com/jgrowl/ansible-playbook-ruby-from-src
rubyTmpDir: /usr/local/src
rubyUrl: http://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.2.tar.gz
rubyCompressedFile: ruby-2.1.2.tar.gz
rubyName: ruby-2.1.2
tmpRubyPath: "{{rubyTmpDir}}/{{rubyName}}"
