---
- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: restart mysql
  service: name={{ mysql_service }} state=restarted

- name: restart nginx
  service: name={{ mysql_service }} state=restarted

- name: reload nginx
  service: name={{ mysql_service }} state=reloaded

- name: set global ruby version
  shell: "rbenv global {{ ruby_version }}"
